In [1]:
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

WARNING:tensorflow:From C:\Users\c23094633\AppData\Roaming\Python\Python311\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
ticker = ["AAPL","TSLA","NVDA"]
stocks = yf.download(ticker, start = "2010-01-01", end = "2021-01-01")
stocks

[*********************100%%**********************]  3 of 3 completed

Price        Adj Close                               Close
Ticker            AAPL        NVDA        TSLA        AAPL        NVDA
Date
2010-01-04    6.470741    4.240229         NaN    7.643214    4.622500  \
2010-01-05    6.481929    4.302145         NaN    7.656429    4.690000
2010-01-06    6.378824    4.329666         NaN    7.534643    4.720000
2010-01-07    6.367032    4.244815         NaN    7.520714    4.627500
2010-01-08    6.409362    4.253987         NaN    7.570714    4.637500
...                ...         ...         ...         ...         ...
2020-12-24  129.514465  129.639206  220.589996  131.970001  129.937500
2020-12-28  134.146637  128.703873  221.229996  136.690002  129.000000
2020-12-29  132.360519  129.135391  221.996674  134.869995  129.432495
2020-12-30  131.231934  131.155731  231.593338  133.720001  131.457504
2020-12-31  130.221069  130.250290  235.223328  132.690002  130.550003

Price                         High                                 Low
Ticker            TSLA        AAPL        NVDA        TSLA        AAPL
Date
2010-01-04         NaN    7.660714    4.655000         NaN    7.585000  \
2010-01-05         NaN    7.699643    4.740000         NaN    7.616071
2010-01-06         NaN    7.686786    4.730000         NaN    7.526786
2010-01-07         NaN    7.571429    4.715000         NaN    7.466071
2010-01-08         NaN    7.571429    4.670000         NaN    7.466429
...                ...         ...         ...         ...         ...
2020-12-24  220.589996  133.460007  131.324997  222.029999  131.100006
2020-12-28  221.229996  137.339996  130.625000  227.133331  133.509995
2020-12-29  221.996674  138.789993  130.725006  223.300003  134.339996
2020-12-30  231.593338  135.990005  132.137497  232.199997  133.399994
2020-12-31  235.223328  134.740005  131.509995  239.573334  131.720001

Price                                     Open
Ticker            NVDA        TSLA        AAPL        NVDA        TSLA
Date
2010-01-04    4.527500         NaN    7.622500    4.627500         NaN  \
2010-01-05    4.605000         NaN    7.664286    4.605000         NaN
2010-01-06    4.642500         NaN    7.656429    4.687500         NaN
2010-01-07    4.592500         NaN    7.562500    4.695000         NaN
2010-01-08    4.562500         NaN    7.510714    4.590000         NaN
...                ...         ...         ...         ...         ...
2020-12-24  129.387497  213.666672  131.320007  130.372498  214.330002
2020-12-28  127.632500  220.266663  133.990005  130.625000  224.836670
2020-12-29  128.422501  218.333328  138.050003  129.250000  220.333328
2020-12-30  128.967499  222.786667  135.580002  129.902496  224.000000
2020-12-31  129.149994  230.373337  134.080002  131.365005  233.330002

Price          Volume
Ticker           AAPL      NVDA         TSLA
Date
2010-01-04  493729600  80020400          NaN
2010-01-05  601904800  72864800          NaN
2010-01-06  552160000  64916800          NaN
2010-01-07  477131200  54779200          NaN
2010-01-08  447610800  47816800          NaN
...               ...       ...          ...
2020-12-24   54930100   9788400   68596800.0
2020-12-28  124486200  21256400   96835800.0
2020-12-29  121047300  17037200   68732400.0
2020-12-30   96452100  22539600  128538000.0
2020-12-31   99116600  19242400  148949700.0

[2769 rows x 18 columns]

In [3]:
stocks.head()

Price      Adj Close                    Close                   High
Ticker          AAPL      NVDA TSLA      AAPL    NVDA TSLA      AAPL   NVDA
Date
2010-01-04  6.470741  4.240229  NaN  7.643214  4.6225  NaN  7.660714  4.655  \
2010-01-05  6.481929  4.302145  NaN  7.656429  4.6900  NaN  7.699643  4.740
2010-01-06  6.378824  4.329666  NaN  7.534643  4.7200  NaN  7.686786  4.730
2010-01-07  6.367032  4.244815  NaN  7.520714  4.6275  NaN  7.571429  4.715
2010-01-08  6.409362  4.253987  NaN  7.570714  4.6375  NaN  7.571429  4.670

Price                 Low                   Open                  Volume
Ticker     TSLA      AAPL    NVDA TSLA      AAPL    NVDA TSLA       AAPL
Date
2010-01-04  NaN  7.585000  4.5275  NaN  7.622500  4.6275  NaN  493729600  \
2010-01-05  NaN  7.616071  4.6050  NaN  7.664286  4.6050  NaN  601904800
2010-01-06  NaN  7.526786  4.6425  NaN  7.656429  4.6875  NaN  552160000
2010-01-07  NaN  7.466071  4.5925  NaN  7.562500  4.6950  NaN  477131200
2010-01-08  NaN  7.466429  4.5625  NaN  7.510714  4.5900  NaN  447610800

Price
Ticker          NVDA TSLA
Date
2010-01-04  80020400  NaN
2010-01-05  72864800  NaN
2010-01-06  64916800  NaN
2010-01-07  54779200  NaN
2010-01-08  47816800  NaN

In [4]:
stocks.tail()

Price        Adj Close                               Close
Ticker            AAPL        NVDA        TSLA        AAPL        NVDA
Date
2020-12-24  129.514465  129.639206  220.589996  131.970001  129.937500  \
2020-12-28  134.146637  128.703873  221.229996  136.690002  129.000000
2020-12-29  132.360519  129.135391  221.996674  134.869995  129.432495
2020-12-30  131.231934  131.155731  231.593338  133.720001  131.457504
2020-12-31  130.221069  130.250290  235.223328  132.690002  130.550003

Price                         High                                 Low
Ticker            TSLA        AAPL        NVDA        TSLA        AAPL
Date
2020-12-24  220.589996  133.460007  131.324997  222.029999  131.100006  \
2020-12-28  221.229996  137.339996  130.625000  227.133331  133.509995
2020-12-29  221.996674  138.789993  130.725006  223.300003  134.339996
2020-12-30  231.593338  135.990005  132.137497  232.199997  133.399994
2020-12-31  235.223328  134.740005  131.509995  239.573334  131.720001

Price                                     Open
Ticker            NVDA        TSLA        AAPL        NVDA        TSLA
Date
2020-12-24  129.387497  213.666672  131.320007  130.372498  214.330002  \
2020-12-28  127.632500  220.266663  133.990005  130.625000  224.836670
2020-12-29  128.422501  218.333328  138.050003  129.250000  220.333328
2020-12-30  128.967499  222.786667  135.580002  129.902496  224.000000
2020-12-31  129.149994  230.373337  134.080002  131.365005  233.330002

Price          Volume
Ticker           AAPL      NVDA         TSLA
Date
2020-12-24   54930100   9788400   68596800.0
2020-12-28  124486200  21256400   96835800.0
2020-12-29  121047300  17037200   68732400.0
2020-12-30   96452100  22539600  128538000.0
2020-12-31   99116600  19242400  148949700.0

In [5]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2769 entries, 2010-01-04 to 2020-12-31
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Adj Close, AAPL)  2769 non-null   float64
 1   (Adj Close, NVDA)  2769 non-null   float64
 2   (Adj Close, TSLA)  2647 non-null   float64
 3   (Close, AAPL)      2769 non-null   float64
 4   (Close, NVDA)      2769 non-null   float64
 5   (Close, TSLA)      2647 non-null   float64
 6   (High, AAPL)       2769 non-null   float64
 7   (High, NVDA)       2769 non-null   float64
 8   (High, TSLA)       2647 non-null   float64
 9   (Low, AAPL)        2769 non-null   float64
 10  (Low, NVDA)        2769 non-null   float64
 11  (Low, TSLA)        2647 non-null   float64
 12  (Open, AAPL)       2769 non-null   float64
 13  (Open, NVDA)       2769 non-null   float64
 14  (Open, TSLA)       2647 non-null   float64
 15  (Volume, AAPL)     2769 non-null   int64
 16  (Volume, NVDA)     2769 non-null   int64
 17  (Volume, TSLA)     2647 non-null   float64
dtypes: float64(16), int64(2)
memory usage: 411.0 KB

In [6]:
#Data reading and writing
stocks.to_csv("stocksML.csv")

In [8]:
stocks = pd.read_csv("stocksML.csv")
stocks

,Price,Adj Close,Adj Close.1,Adj Close.2,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-04,6.470740795135498,4.24022912979126,NaN,7.643214225769043,4.622499942779541,NaN,7.660714149475098,4.65500020980835,NaN,7.585000038146973,4.527500152587891,NaN,7.622499942779541,4.627500057220459,NaN,493729600,80020400,NaN
3,2010-01-05,6.481929302215576,4.302145004272461,NaN,7.656428813934326,4.690000057220459,NaN,7.699643135070801,4.739999771118164,NaN,7.6160712242126465,4.605000019073486,NaN,7.664286136627197,4.605000019073486,NaN,601904800,72864800,NaN
4,2010-01-06,6.378823757171631,4.3296661376953125,NaN,7.534643173217773,4.71999979019165,NaN,7.68678617477417,4.730000019073486,NaN,7.526785850524902,4.642499923706055,NaN,7.656428813934326,4.6875,NaN,552160000,64916800,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2766,2020-12-24,129.51446533203125,129.6392059326172,220.58999633789062,131.97000122070312,129.9375,220.58999633789062,133.4600067138672,131.3249969482422,222.02999877929688,131.10000610351562,129.3874969482422,213.6666717529297,131.32000732421875,130.37249755859375,214.3300018310547,54930100,9788400,68596800.0
2767,2020-12-28,134.14663696289062,128.70387268066406,221.22999572753906,136.69000244140625,129.0,221.22999572753906,137.33999633789062,130.625,227.13333129882812,133.50999450683594,127.63249969482422,220.26666259765625,133.99000549316406,130.625,224.836669921875,124486200,21256400,96835800.0
2768,2020-12-29,132.3605194091797,129.13539123535156,221.99667358398438,134.8699951171875,129.4324951171875,221.99667358398438,138.7899932861328,130.72500610351562,223.3000030517578,134.33999633789062,128.42250061035156,218.3333282470703,138.0500030517578,129.25,220.3333282470703,121047300,17037200,68732400.0
2769,2020-12-30,131.23193359375,131.15573120117188,231.5933380126953,133.72000122070312,131.45750427246094,231.5933380126953,135.99000549316406,132.1374969482422,232.1999969482422,133.39999389648438,128.96749877929688,222.7866668701172,135.5800018310547,129.90249633789062,224.0,96452100,22539600,128538000.0
2770,2020-12-31,130.2210693359375,130.2502899169922,235.22332763671875,132.69000244140625,130.5500030517578,235.22332763671875,134.74000549316406,131.50999450683594,239.57333374023438,131.72000122070312,129.14999389648438,230.3733367919922,134.0800018310547,131.36500549316406,233.3300018310547,99116600,19242400,148949700.0

In [11]:
stocks.columns = stocks.columns.to_flat_index()
stocks.columns

Index(['Price', 'Adj Close', 'Adj Close.1', 'Adj Close.2', 'Close', 'Close.1',
       'Close.2', 'High', 'High.1', 'High.2', 'Low', 'Low.1', 'Low.2', 'Open',
       'Open.1', 'Open.2', 'Volume', 'Volume.1', 'Volume.2'],
      dtype='object')

In [12]:
stocks

,Price,Adj Close,Adj Close.1,Adj Close.2,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA,AAPL,NVDA,TSLA
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-04,6.470740795135498,4.24022912979126,NaN,7.643214225769043,4.622499942779541,NaN,7.660714149475098,4.65500020980835,NaN,7.585000038146973,4.527500152587891,NaN,7.622499942779541,4.627500057220459,NaN,493729600,80020400,NaN
3,2010-01-05,6.481929302215576,4.302145004272461,NaN,7.656428813934326,4.690000057220459,NaN,7.699643135070801,4.739999771118164,NaN,7.6160712242126465,4.605000019073486,NaN,7.664286136627197,4.605000019073486,NaN,601904800,72864800,NaN
4,2010-01-06,6.378823757171631,4.3296661376953125,NaN,7.534643173217773,4.71999979019165,NaN,7.68678617477417,4.730000019073486,NaN,7.526785850524902,4.642499923706055,NaN,7.656428813934326,4.6875,NaN,552160000,64916800,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2766,2020-12-24,129.51446533203125,129.6392059326172,220.58999633789062,131.97000122070312,129.9375,220.58999633789062,133.4600067138672,131.3249969482422,222.02999877929688,131.10000610351562,129.3874969482422,213.6666717529297,131.32000732421875,130.37249755859375,214.3300018310547,54930100,9788400,68596800.0
2767,2020-12-28,134.14663696289062,128.70387268066406,221.22999572753906,136.69000244140625,129.0,221.22999572753906,137.33999633789062,130.625,227.13333129882812,133.50999450683594,127.63249969482422,220.26666259765625,133.99000549316406,130.625,224.836669921875,124486200,21256400,96835800.0
2768,2020-12-29,132.3605194091797,129.13539123535156,221.99667358398438,134.8699951171875,129.4324951171875,221.99667358398438,138.7899932861328,130.72500610351562,223.3000030517578,134.33999633789062,128.42250061035156,218.3333282470703,138.0500030517578,129.25,220.3333282470703,121047300,17037200,68732400.0
2769,2020-12-30,131.23193359375,131.15573120117188,231.5933380126953,133.72000122070312,131.45750427246094,231.5933380126953,135.99000549316406,132.1374969482422,232.1999969482422,133.39999389648438,128.96749877929688,222.7866668701172,135.5800018310547,129.90249633789062,224.0,96452100,22539600,128538000.0
2770,2020-12-31,130.2210693359375,130.2502899169922,235.22332763671875,132.69000244140625,130.5500030517578,235.22332763671875,134.74000549316406,131.50999450683594,239.57333374023438,131.72000122070312,129.14999389648438,230.3733367919922,134.0800018310547,131.36500549316406,233.3300018310547,99116600,19242400,148949700.0

In [10]:
stocks.describe()

,Price,Adj Close,Adj Close.1,Adj Close.2,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
count,2771,2770,2770,2648,2770,2770,2648,2770,2770,2648,2770,2770,2648,2770,2770,2648,2770,2770,2648
unique,2771,2731,2423,2457,2658,2127,2457,2635,2106,2356,2649,2105,2366,2654,2086,2363,2763,2750,2622
top,Ticker,25.121416091918945,3.359619617462158,1.8279999494552612,31.649999618530273,3.609999895095825,1.8279999494552612,43.75,3.7174999713897705,2.299999952316284,23.8125,3.5950000286102295,1.8200000524520874,18.75,3.140000104904175,2.0,118655600,30158400,131184000.0
freq,1,2,5,4,3,7,4,3,9,7,3,10,6,4,8,6,2,2,2

In [ ]:
dataset_train = pd.read_csv('/content/stock_Price.csv')
training_set = dataset_train.iloc[:, 1:2].values
training_set

array([[ 10.02681076],
       [ 10.15250891],
       [ 10.03647982],
       ...,
       [204.45038832],
       [202.9670384 ],
       [201.39642663]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range = (0,1))

training_set_scaled = sc.fit_transform(training_set)

In [ ]:
training_set_scaled

array([[0.00181889],
       [0.00241002],
       [0.00186436],
       ...,
       [0.91615248],
       [0.9091766 ],
       [0.90179034]])

In [ ]:
x_train = []

y_train = []

for i in range(60, 5724):
  x_train.append(training_set_scaled[i-60:i,0])
  y_train.append(training_set_scaled[i, 0])

x_train , y_train = np.array(x_train), np.array(y_train)

# Reshaping

In [ ]:
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

In [ ]:
x_train.shape

(5664, 60, 1)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

Neurons

In [ ]:
regressor = Sequential()

regressor.add(LSTM(units = 50, return_sequences= True, input_shape = ( x_train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences= True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences= True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

Output Layer

In [ ]:
regressor.add(Dense(units = 1))

Compiling RNN

In [ ]:
regressor.compile(optimizer='adam', loss= 'mean_squared_error')

Fitting the RNN

In [ ]:
regressor.fit(x_train, y_train, epochs= 100, batch_size= 32)

Epoch 1/100
177/177 [==============================] - 25s 98ms/step - loss: 0.0026
Epoch 2/100
177/177 [==============================] - 17s 97ms/step - loss: 7.4107e-04
Epoch 3/100
177/177 [==============================] - 18s 105ms/step - loss: 7.7645e-04
Epoch 4/100
177/177 [==============================] - 17s 98ms/step - loss: 6.8452e-04
Epoch 5/100
177/177 [==============================] - 18s 100ms/step - loss: 6.0041e-04
Epoch 6/100
177/177 [==============================] - 19s 109ms/step - loss: 6.6253e-04
Epoch 7/100
177/177 [==============================] - 18s 102ms/step - loss: 5.7782e-04
Epoch 8/100
177/177 [==============================] - 18s 105ms/step - loss: 4.9594e-04
Epoch 9/100
177/177 [==============================] - 17s 98ms/step - loss: 4.9930e-04
Epoch 10/100
177/177 [==============================] - 18s 103ms/step - loss: 4.1749e-04
Epoch 11/100
177/177 [==============================] - 18s 102ms/step - loss: 5.4575e-04
Epoch 12/100
177/177 [==============================] - 17s 98ms/step - loss: 5.9288e-04
Epoch 13/100
177/177 [==============================] - 19s 105ms/step - loss: 4.4765e-04
Epoch 14/100
177/177 [==============================] - 17s 98ms/step - loss: 4.1465e-04
Epoch 15/100
177/177 [==============================] - 19s 107ms/step - loss: 4.6331e-04
Epoch 16/100
177/177 [==============================] - 18s 104ms/step - loss: 3.7257e-04
Epoch 17/100
177/177 [==============================] - 17s 98ms/step - loss: 4.4440e-04
Epoch 18/100
177/177 [==============================] - 19s 105ms/step - loss: 4.3718e-04
Epoch 19/100
177/177 [==============================] - 17s 98ms/step - loss: 4.8154e-04
Epoch 20/100
177/177 [==============================] - 17s 99ms/step - loss: 5.4006e-04
Epoch 21/100
177/177 [==============================] - 19s 105ms/step - loss: 5.3851e-04
Epoch 22/100
177/177 [==============================] - 18s 99ms/step - loss: 3.9655e-04
Epoch 23/100
177/177 [==============================] - 18s 103ms/step - loss: 3.9955e-04
Epoch 24/100
177/177 [==============================] - 18s 101ms/step - loss: 4.0208e-04
Epoch 25/100
177/177 [==============================] - 18s 99ms/step - loss: 4.6711e-04
Epoch 26/100
177/177 [==============================] - 19s 106ms/step - loss: 4.0360e-04
Epoch 27/100
177/177 [==============================] - 17s 98ms/step - loss: 3.8293e-04
Epoch 28/100
177/177 [==============================] - 18s 100ms/step - loss: 3.9362e-04
Epoch 29/100
177/177 [==============================] - 18s 104ms/step - loss: 3.9726e-04
Epoch 30/100
177/177 [==============================] - 18s 99ms/step - loss: 3.8384e-04
Epoch 31/100
177/177 [==============================] - 19s 106ms/step - loss: 3.9699e-04
Epoch 32/100
177/177 [==============================] - 17s 99ms/step - loss: 3.8068e-04
Epoch 33/100
177/177 [==============================] - 18s 99ms/step - loss: 3.6654e-04
Epoch 34/100
177/177 [==============================] - 19s 106ms/step - loss: 4.4401e-04
Epoch 35/100
177/177 [==============================] - 17s 99ms/step - loss: 3.8357e-04
Epoch 36/100
177/177 [==============================] - 18s 104ms/step - loss: 4.6941e-04
Epoch 37/100
177/177 [==============================] - 18s 100ms/step - loss: 3.6110e-04
Epoch 38/100
177/177 [==============================] - 18s 99ms/step - loss: 3.9866e-04
Epoch 39/100
177/177 [==============================] - 19s 106ms/step - loss: 3.8177e-04
Epoch 40/100
177/177 [==============================] - 18s 99ms/step - loss: 3.4594e-04
Epoch 41/100
177/177 [==============================] - 18s 102ms/step - loss: 3.4674e-04
Epoch 42/100
177/177 [==============================] - 18s 102ms/step - loss: 3.6333e-04
Epoch 43/100
177/177 [==============================] - 18s 99ms/step - loss: 4.1434e-04
Epoch 44/100
177/177 [==============================] - 19s 106ms/step - loss: 3.6719e-04
Epoch 45/100
177/177 [==============================] - 18s 100ms/step - loss: 3.9986e-04
Epoch 46/100
177/177 [==============================] - 18s 99ms/step - loss: 3.9965e-04
Epoch 47/100
177/177 [==============================] - 19s 105ms/step - loss: 3.7144e-04
Epoch 48/100
177/177 [==============================] - 17s 99ms/step - loss: 3.3314e-04
Epoch 49/100
177/177 [==============================] - 19s 106ms/step - loss: 3.6802e-04
Epoch 50/100
177/177 [==============================] - 18s 99ms/step - loss: 3.8732e-04
Epoch 51/100
177/177 [==============================] - 18s 100ms/step - loss: 3.3349e-04
Epoch 52/100
177/177 [==============================] - 19s 106ms/step - loss: 3.3397e-04
Epoch 53/100
177/177 [==============================] - 17s 99ms/step - loss: 3.7182e-04
Epoch 54/100
177/177 [==============================] - 18s 104ms/step - loss: 3.4432e-04
Epoch 55/100
177/177 [==============================] - 18s 100ms/step - loss: 3.2388e-04
Epoch 56/100
177/177 [==============================] - 18s 99ms/step - loss: 3.6903e-04
Epoch 57/100
177/177 [==============================] - 19s 105ms/step - loss: 3.4632e-04
Epoch 58/100
177/177 [==============================] - 19s 106ms/step - loss: 4.4318e-04
Epoch 59/100
177/177 [==============================] - 18s 100ms/step - loss: 3.4342e-04
Epoch 60/100
177/177 [==============================] - 19s 104ms/step - loss: 3.1115e-04
Epoch 61/100
177/177 [==============================] - 17s 98ms/step - loss: 3.1666e-04
Epoch 62/100
177/177 [==============================] - 19s 105ms/step - loss: 3.4422e-04
Epoch 63/100
177/177 [==============================] - 18s 99ms/step - loss: 3.1975e-04
Epoch 64/100
177/177 [==============================] - 18s 100ms/step - loss: 3.0188e-04
Epoch 65/100
177/177 [==============================] - 19s 106ms/step - loss: 3.1754e-04
Epoch 66/100
177/177 [==============================] - 18s 100ms/step - loss: 3.3928e-04
Epoch 67/100
177/177 [==============================] - 18s 104ms/step - loss: 3.1545e-04
Epoch 68/100
177/177 [==============================] - 18s 100ms/step - loss: 3.5567e-04
Epoch 69/100
177/177 [==============================] - 18s 99ms/step - loss: 3.6321e-04
Epoch 70/100
177/177 [==============================] - 19s 106ms/step - loss: 3.0961e-04
Epoch 71/100
177/177 [==============================] - 18s 99ms/step - loss: 3.3496e-04
Epoch 72/100
177/177 [==============================] - 18s 101ms/step - loss: 3.0916e-04
Epoch 73/100
177/177 [==============================] - 18s 103ms/step - loss: 3.0144e-04
Epoch 74/100
177/177 [==============================] - 18s 99ms/step - loss: 3.3197e-04
Epoch 75/100
177/177 [==============================] - 19s 106ms/step - loss: 3.2203e-04
Epoch 76/100
177/177 [==============================] - 18s 100ms/step - loss: 3.3028e-04
Epoch 77/100
177/177 [==============================] - 18s 100ms/step - loss: 3.6299e-04
Epoch 78/100
177/177 [==============================] - 19s 106ms/step - loss: 3.4658e-04
Epoch 79/100
177/177 [==============================] - 18s 100ms/step - loss: 3.0789e-04
Epoch 80/100
177/177 [==============================] - 19s 106ms/step - loss: 3.1182e-04
Epoch 81/100
177/177 [==============================] - 18s 100ms/step - loss: 2.9871e-04
Epoch 82/100
177/177 [==============================] - 18s 99ms/step - loss: 3.6904e-04
Epoch 83/100
177/177 [==============================] - 19s 107ms/step - loss: 3.0095e-04
Epoch 84/100
177/177 [==============================] - 18s 100ms/step - loss: 3.2490e-04
Epoch 85/100
177/177 [==============================] - 19s 106ms/step - loss: 3.1594e-04
Epoch 86/100
177/177 [==============================] - 18s 99ms/step - loss: 3.4053e-04
Epoch 87/100
177/177 [==============================] - 18s 99ms/step - loss: 3.3436e-04
Epoch 88/100
177/177 [==============================] - 19s 106ms/step - loss: 3.2480e-04
Epoch 89/100
177/177 [==============================] - 18s 99ms/step - loss: 3.2049e-04
Epoch 90/100
177/177 [==============================] - 18s 104ms/step - loss: 2.7110e-04
Epoch 91/100
177/177 [==============================] - 18s 102ms/step - loss: 3.1466e-04
Epoch 92/100
177/177 [==============================] - 18s 99ms/step - loss: 2.9515e-04
Epoch 93/100
177/177 [==============================] - 19s 106ms/step - loss: 3.4170e-04
Epoch 94/100
177/177 [==============================] - 18s 99ms/step - loss: 3.1250e-04
Epoch 95/100
177/177 [==============================] - 18s 103ms/step - loss: 3.3592e-04
Epoch 96/100
177/177 [==============================] - 18s 103ms/step - loss: 2.9752e-04
Epoch 97/100
177/177 [==============================] - 18s 99ms/step - loss: 2.6938e-04
Epoch 98/100
177/177 [==============================] - 19s 106ms/step - loss: 3.4483e-04
Epoch 99/100
177/177 [==============================] - 18s 99ms/step - loss: 3.0808e-04
Epoch 100/100
177/177 [==============================] - 18s 100ms/step - loss: 2.7599e-04